name = "moresult"
version = "1.1.0"

description = "Ergonomic Result utilities for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "ivamly", repo = "moresult" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
